Gestion_Stagiaire/Controllers/StagiairesController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using OfficeOpenXml;
using Gestion_Stagiaire.Data;
using Gestion_Stagiaire.Models;
using Gestion_Stagiaires.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using X.PagedList;
using DocumentFormat.OpenXml.Office2010.Excel;


namespace Gestion_Stagiaire.Controllers
{
    [Authorize]
    public class StagiairesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StagiairesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string searchString, int? page)
        {
            // Store the search term in ViewData to retain it in the form and pagination links
            ViewData["CurrentFilter"] = searchString;
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            // Get the user's role
            var userRole = User.FindFirst(ClaimTypes.Role)?.Value;

            // Base query to retrieve all stagiaires
            var stagiaires = _context.Stagiaires.AsQueryable();

            if (userRole == "Stagiaire")
            {
                stagiaires = stagiaires.Where(s => s.Id.ToString() == userId);
            }

            // Apply the search filter
            if (!string.IsNullOrEmpty(searchString))
            {
                stagiaires = stagiaires.Where(s => s.Nom.Contains(searchString)
                                                || s.Prenom.Contains(searchString)
                                                || s.Cin.ToString().Contains(searchString)
                                                || s.Telephone.ToString().Contains(searchString)
                                                || s.Ecole.Contains(searchString)); // Ensure Ecole is compared correctly
            }

            // Pagination parameters
            int pageNumber = page ?? 1; // Default to page 1 if null
            int pageSize = 10;          // Number of items per page

            // Apply pagination
            var paginatedStagiaires = await stagiaires.ToPagedListAsync(pageNumber, pageSize);

            return View(paginatedStagiaires);
        }



        // GET: Stagiaires/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stagiaire = await _context.Stagiaires
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stagiaire == null)
            {
                return NotFound();
            }

            return View(stagiaire);
        }

        // GET: Stagiaires/Create
        public async Task<IActionResult> Create()
        {

            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            ViewBag.UserEmail = userEmail;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nom,Prenom,Cin,Telephone,Email, Ecole")] Stagiaire stagiaire, IFormFile Path_Photo, IFormFile Path_CV)
        {
            if (ModelState.IsValid)
            {
                // Ensure the user is authenticated
                if (User.Identity?.IsAuthenticated == true)
                {
                    foreach (var claim in User.Claims)
                    {
                        Console.WriteLine($"Claim Type: {claim.Type}, Claim Value: {claim.Value}");
                    }
                    // Retrieve user information
                    string? userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                    //var userEmail = User.Identity?.Name;
                    var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
                    if (!string.IsNullOrEmpty(userId))
                    {
                        Console.WriteLine($"Authenticated User ID: {userId}");

                        // Only check for existing stagiaire email if the user is a "stagiaire" (not "rh")
                        if (User.IsInRole("Stagiaire"))
                        {
                            // Check if a Stagiaire with the same email already exists
                            var existingStagiaire = await _context.Stagiaires
                                .FirstOrDefaultAsync(s => s.Email == userEmail);
                            stagiaire.Email = userEmail;


                            if (existingStagiaire != null)
                            {
                                // If an account already exists for "stagiaire", set an error message in ViewData for the popup
                                ModelState.AddModelError(string.Empty, "You have already created an account.");
                                return View(stagiaire);
                            }
                            else
                            {
                                // Assign the user's ID (stagiaire)
                                stagiaire.Id = Guid.Parse(userId); // User's ID (stagiaire)
                            }
                        }
                        else if (User.IsInRole("RH"))
                        {
                            // If the user is "rh", generate a new GUID for the Stagiaire ID
                            stagiaire.Id = Guid.NewGuid(); // New random ID for "rh"
                        }

                        // Assign the user email to stagiaire (optional, as it's already included)
                    }
                    else
                    {
                        Console.WriteLine("User ID claim is not available.");
                        ModelState.AddModelError(string.Empty, "Failed to retrieve user ID. Please try again.");
                        return View(stagiaire);
                    }
                }
                else
                {
                    Console.WriteLine("User is not authenticated.");
                    ModelState.AddModelError(string.Empty, "User is not authenticated. Please log in.");
                    return View(stagiaire);
                }

                // Handle Photo upload
                if (!await HandleFileUpload(Path_Photo, stagiaire, "photos", "Path_Photo", ".png"))
                {
                    return View(stagiaire);
                }

                // Handle CV upload
                if (!await HandleFileUpload(Path_CV, stagiaire, "cvs", "Path_CV", ".pdf"))
                {
                    return View(stagiaire);
                }

                // Save to the database
                _context.Add(stagiaire);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // Return the view with the model if validation fails
            return View(stagiaire);
        }


        // GET: Stagiaires/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stagiaire = await _context.Stagiaires.FindAsync(id);
            if (stagiaire == null)
            {
                return NotFound();
            }

            return View(stagiaire);
        }

        // POST: Stagiaires/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Nom,Prenom,Cin,Telephone,Email,Ecole,Path_Photo,Path_CV")] Stagiaire stagiaire, IFormFile? Path_Photo, IFormFile? Path_CV)
        {
            if (id != stagiaire.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Retrieve the existing record from the database
                    var existingStagiaire = await _context.Stagiaires.FindAsync(id);
                    if (existingStagiaire == null)
                    {
                        return NotFound();
                    }

                    // Handle Photo upload if a new one is provided
                    if (Path_Photo != null && Path_Photo.Length > 0)
                    {
                        var fileExtension = Path.GetExtension(Path_Photo.FileName).ToLower();
                        if (fileExtension != ".png")
                        {
                            ModelState.AddModelError("Path_Photo", "La photo doit être un fichier .png.");
                            return View(stagiaire);
                        }

                        var uploadsFolder = Path.Combine("wwwroot/uploads/photos");
                        Directory.CreateDirectory(uploadsFolder);

                        var filePath = Path.Combine(uploadsFolder, $"{stagiaire.Id}.png");  // Append "_photo" to avoid overwriting
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await Path_Photo.CopyToAsync(stream);
                        }

                        stagiaire.Path_Photo = $"{stagiaire.Id}.png"; // Update Path_Photo
                    }
                    else
                    {
                        // Preserve the existing Path_Photo if no new photo is uploaded
                        stagiaire.Path_Photo = existingStagiaire.Path_Photo;
                    }

                    // Handle CV upload if a new one is provided
                    if (Path_CV != null && Path_CV.Length > 0)
                    {
                        var fileExtension = Path.GetExtension(Path_CV.FileName).ToLower();
                        if (fileExtension != ".pdf")
                        {
                            ModelState.AddModelError("Path_CV", "Le CV doit être un fichier .pdf.");

Gestion_Stagiaire/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gestion_Stagiaire.Data;
using Gestion_Stagiaire.Models;
using Microsoft.AspNetCore.Authorization;

namespace Gestion_Stagiaire.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StatusController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StatusController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Status
        public async Task<IActionResult> Index()
        {
            return View(await _context.Statuses.ToListAsync());
        }

        // GET: Status/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Statuses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        // GET: Status/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Status/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Reponse")] Status status)
        {
            if (ModelState.IsValid)
            {
                status.Id = Guid.NewGuid();
                _context.Add(status);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }

        // GET: Status/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Statuses.FindAsync(id);
            if (status == null)
            {
                return NotFound();
            }
            return View(status);
        }

        // POST: Status/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Reponse")] Status status)
        {
            if (id != status.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(status);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StatusExists(status.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }

        // GET: Status/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Statuses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        // POST: Status/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var status = await _context.Statuses.FindAsync(id);
            if (status != null)
            {
                _context.Statuses.Remove(status);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StatusExists(Guid id)
        {
            return _context.Statuses.Any(e => e.Id == id);
        }
    }
}

Gestion_Stagiaire/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestion_Stagiaire</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Gestion_Stagiaire.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">




</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <!-- Logo -->
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/image1.png" alt="Logo" class="navbar-logo" /> <!-- Remplacez 'image1.png' par le nom exact de votre fichier d'image -->
                    
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fas fa-home"></i> <!-- Icône de maison -->
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" href="https://www.wicmicgroup.com/" >À Propos</a>
                        </li>

                        @if (User.IsInRole("Admin") )
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Stagiaires" asp-action="Index">Stagiaire</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="DemandeStages" asp-action="Index">Demande Stage</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Type_Stage" asp-action="Index">Type stage</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Departements" asp-action="Index">Département</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Status" asp-action="Index">Statut</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/AdminRegister">Ajouter Utilisateurs</a>

                            </li>
                        }
                        @if (User.IsInRole("RH"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Stagiaires" asp-action="Index">Stagiaire</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="DemandeStages" asp-action="Index">Demande Stage</a>
                            </li>
                        }
                        @if (User.IsInRole("Stagiaire"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Stagiaires" asp-action="Index" >Mon Profil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="DemandeStages" asp-action="Index" >Mes Demandes </a>
                            </li>

                        }

                       

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
<footer class="footer bg-dark text-light py-5">
    <div class="container">
        <!-- Première rangée : Informations principales -->
        <div class="row">
            <div class="col-lg-4 text-center text-lg-start mb-4">
                <img src="~/images/image1.png" alt="Logo" class="img-fluid mb-3" style="max-width: 150px;">
               
            </div>
            <div class="col-lg-4 text-center mb-4">
                <h5 class="text-uppercase mb-3">Contact</h5>
                <ul class="list-unstyled">
                    <li><i class="fas fa-map-marker-alt"></i> Route de Metline, 7070 Ras Jebel, Bizerte</li>
                    <li><i class="fas fa-phone"></i> +216 72 456 026</li>
                    <li><i class="fas fa-envelope"></i> <a href="mailto:contact@wic-sa.com" class="text-warning">contact@wic-sa.com</a></li>
                </ul>
            </div>
            <div class="col-lg-4 text-center text-lg-end mb-4">
                <h5 class="text-uppercase mb-3">Suivez-nous</h5>
                <div class="d-flex justify-content-center justify-content-lg-end">
                    <a href="https://www.facebook.com/wicmicgroup" target="_blank" class="text-light mx-2">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a>
                    <a href="https://www.instagram.com/wicmicgroup/" target="_blank" class="text-light mx-2">
                        <i class="fab fa-instagram fa-2x"></i>
                    </a>
                    <a href="https://tn.linkedin.com/company/washing-international-company" target="_blank" class="text-light mx-2">
                        <i class="fab fa-linkedin fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>

        <!-- Deuxième rangée : Liens rapides -->
        <div class="row border-top pt-4 mt-4">
            <div class="col-md-6 text-center text-md-start mb-3">
                <h5 class="text-uppercase">Liens rapides</h5>
                <ul class="list-inline">
                        <li class="list-inline-item"><a class="text-light" asp-area="" asp-controller="DemandeStages" asp-action="Index">Gérer les Demandes</a></li>
                        <li class="list-inline-item"><a class="text-light" href="https://www.wicmicgroup.com/">À Propos</a></li>
                </ul>
            </div>

        </div>

        <!-- Troisième rangée : Copyright -->
        <div class="row mt-4">
            <div class="col text-center">
                <small>&copy; 2025 WicMic - Tous droits réservés.</small>
            </div>
        </div>
    </div>

</footer>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>